### ISSUE TITLE
market_orders doesn't exist

### ISSUE THREAD

**Issue by metalicork64** [broderickhyman/albiondata-sql-dotNet#1]
Running Program.cs after freshly setting up the server and running create-historical-procedures results in errors when attempting to handel market orders. It appears that market_orders doesn't exist and is never created. I've tried with just the -n and -s flags as well as both and they all result in the same errors. The "Table 'albion.market_orders' doesn't exist" is said to originate from line 125 of Program.cs.

**Comment by broderickhyman** [comment]
I believe you may not have had the proper database selected as I just successfully used the create-historical-procedures on a fresh instance
